# Choose Your Tools {#choose}

TODO: add intro for revised chapter

## Start Sketching Your Data Story {- #sketch}

Before we dive into visualization software, push away the computer. Let's start by focusing on the important part---our story---pick up some of our favorite old-school tools:

  - several blank sheets of paper
  - colored pencils, pens, or markers
  - your imagination

We design visualizations to help us tell our *data story*, the narrative that draws attention to meaningful patterns and keys insights about the information we're collecting. But in the early stage of the process, a common problem is that we don't yet have a clear sense of the pieces of our story, or how it all fits together. That's perfectly normal. We have have partially-formed ideas swirling around in our heads, and need ways to get them out, with a quick scribble-and-sketch exercise:

1. On the first sheet of blank paper, *write the problem*.. Sometimes information problems are best posed as a question to be answered... Perhaps the goal is to answer a question... if so, write down the question.... - Is it in the form of a question? If so, figure out how to pose the question. [Use some of this from ch 3? -- Start the process by writing down your question---literally in the form of a question, punctuated with a question mark---to clarify your own thinking, and also so that you can clearly communicate it to others who may be assisting you. All too often, our brains automatically jump ahead to try to identify the *answer*, without reflecting on the best way frame the *question* in a way that does not limit the range of possible results.]....Whatever form it takes in your head, write out the words that come to mind.

2. On the next sheet of paper, *write keywords about data* you need to find, or have already collected, to address the problem or question above. For example, keywords might include "prior learning experience" or "priorities for local government" or "median family income". *Draw arrows* to show where the data might come from, such as "online student survey" or "neighborhood interviews" or "census website."

3. On the next sheet of paper, *draw a quick sketch of a type of visualization* you're thinking about creating. ...No artistic skills are required. Just use your imagination.
- Do you envision some type of chart? Sketch a picture.
- Or do you imagine some type of map? Show what it might look like.
- Will your visualization be interactive? Insert arrows, buttons, whatever.
... No artistic skill is required. Nor do we expect you to have real data at this stage. Simply add "placeholder" points or lines or shapes to represent the patterns you might display in your finished visualization, depending on what it actually shows.

TODO: insert two different three-panel illustrations of problem, data, and visualization

This quick scribble-and-sketch exercise helps you to start framing your data story. To be sure, there's much more work to be done, such as finding, cleaning, and visualizing data, which we'll cover in the chapters to come. But transferring ideas from your brain onto paper is the big first step, because making your thoughts visible enables you to easily act on them. Scribbling words and sketching pictures not only helps *you* to see your thoughts more clearly, but it also allows you to share what's been inside your head more concretely with friends and colleagues. After reflecting on your sheets of paper and listening to feedback, you can cross out not-so-good ideas, replace them with better ones, and add new sheets of paper with more ideas. If your initial thoughts seem too complex or confusing, simplify them by breaking them down into more coherent pieces, each on its own sheet of paper. Finally, you can spread out all of your sheets on a table, move them around to possibly reorder the sequence, and begin to define the three essential stages of your data story: the beginning, middle, and end. Imagine your sheets of paper as a storyboard to organize your presentation slides, or to weave paragraphs and pictures for your written report or website. After you've learned more steps about the data visualization process by reading the body of this book, we'll come back to this exercise at the end in [Chapter 15: Telling Your Data Story](story.html)


Now you have a clearer sense of the story you wish to tell, and some preliminary ideas about what types of data visualizations you might wish to create. In the next section we'll introduce some of the factors you should consider when choosing digital tools.

## Tools and Tradeoffs {- #tools-tradeoffs}
If you feel overwhelmed by the avalanche of digital tools available today, you're not alone. When you're simply trying to do your regular work, keeping up with all of the latest software applications can feel like an additional part-time job you didn't sign up for. Digital tools are constantly changing and evolving. That's good news if you like to experiment and choose among several options, but not-so-good news if you lack the time to make complex decisions.

To help organize your time and decision-making process, we have listed ten key factors that we consider when evaluating a new digital tool or online service. When comparing options, many decisions involve some type of tradeoff, a balance between competing wants and needs, such as ease-of-use versus extensive features. By identifying key factors, we believe that each reader can make a more informed decision about which tools offer the best tradeoff for you, since all of us are different. Furthermore, we worded our categories broadly, because the concepts can be applied to other areas of your digital life, but followed up with more context about data visualization in particular.

*1. Easy-to-learn*

How much time will be required to learn a new tool? In our busy lives, this is often the most important factor, but also one that varies widely, as your personal investment of time and energy depends on your prior experience in using related tools and grasping key concepts. In this book, we use the label *Easy Tools* to identify those best suited for beginners (and even some advanced users prefer them, too). They usually feature a graphical user interface, meaning you operate them with pull-down menus or drag-and-drop steps, rather than memorizing commands to be typed into a blank screen. The better ones also offer user-friendly error messages that guide you in the right direction after a wrong turn. Later in the book, we'll introduce *Power Tools* that provide more control and customization of your visualizations, such as code templates that you can copy and edit, which is easier than writing them from scratch. Overall, when deciding which tools to include in this book, we placed easy-to-learn at the top of our list. In fact, we removed a popular free drag-and-drop tool from an earlier draft of this book because even *we* had difficulty following our own instructions in how to use it. When faced with several good options, choose simplicity.

*2. Free or Affordable*

Is the tool free to use? Or is it based on a *freemium* model that offers basic functions for free, with premium features at a price? Or does it require paying a one-time purchase or monthly subscription fee? Of course, the answer to what is affordable will vary for each reader. Of course, we fully understand that the business model for many software developers requires steady revenue, and both of us willingly pay to use specific tools necessary for our work. If you regularly rely on a tool to do your job, with no clear alternative, it's in your best interest to financially support their continued existence. But when creating this book, we were impressed by the wide array of high-quality data visualization tools that are available at no cost to users. To increase access to data visualization for all readers, every tool we recommend is free, or its core features are freely available.

*3. Powerful*

Does the tool offer all of the features you anticipate needing? For example, does it support building sufficient types of data visualizations for your project? Although more is usually better, some types of charts are obscure and rarely used, such as [radar charts](https://en.wikipedia.org/wiki/Radar_chart) and [waterfall charts](https://en.wikipedia.org/wiki/Waterfall_chart). Also, look out for limits on the amount of data you can upload, or restrictions on visualizations you create. For example, we removed a freemium tool from an earlier version of this book because the company began to require a paid license if your map was viewed more than 100 times on the web. Furthermore, to what extent does the tool allow you to customize the appearance of your visualizations? Since drag-and-drop and freemium tools commonly limit your display options, you may need to make tradeoffs between them versus more powerful and customizable tools. In this book, we begin with easy tools and gradually introduce more advanced ones in each chapter, to help you identify your ideal combination of simplicity and power.

*4. Supported*

Does the developer regularly maintain and update the tool, and respond to questions or issues? Is there an active user community that supports the tool and shares its knowledge about using it? If you've worked with digital tools as long as we have, you'll recognize our pain in losing several whose developers pulled the plug. For example, the [Killed By Google](http://killedbygoogle.com) lists nearly 200 applications and online services that this multi-billion dollar corporation closed down. One of these was a popular data visualization tool, [Google Fusion Tables](https://en.wikipedia.org/wiki/Google_Fusion_Tables), which once occupied a full chapter in an earlier version of this book, when we removed when Google shut down the tool after a ten-year run in 2019. Although none of us can predict which online tools will persist in future years, we looked for signs of active support before including them in this book, such as regular updates, stars earned on a [GitHub](http://github.com) developer's site, and questions answered in the [StackOverflow](http://stackoverflow.com) user forum. But never assume that the future will resemble the past. The continuous evolution of digital tools means that some become extinct.

*5. Portable*

How easily can you migrate your data *into* and *out* of a tool? For example, we stopped recommending an online story map tool created by a well-known software company when we discovered that while users could easily upload locations, text, and photos, but there was no way to export all of their work! As digital technology inevitably changes, all data will need to migrate to another platform, and it's your job to be prepared for this eventual transition. Think about the issue as historical preservation, to increase the likelihood that your projects will continue to function on some unknown platform in the future. If your current tool developer announced that it was shutting down next month, could you easily extract all of the underlying data in a commonly-used file format to upload to a different tool? A key step to future-proof your visualizations is to ensure that your data files are easily separated from the presentation software that generates the charts or maps. When recommending tools for this book, we favored those that support portable data downloads for future migrations.

*6. Secure and Private*

This category combines related questions about security and privacy. First, does the online tool or service take reasonable precautions to protect your personal information from malicious hackers and malware? Review a [list of major data breaches on Wikipedia](https://en.wikipedia.org/wiki/List_of_data_breaches) to help you make informed decisions. If your tool developer recently experienced a malicious data hack, find out how they responded. Second, when you access tools through your browser, does they track your web activity across different sites? Consider installing the free [Privacy Badger browser extension from the Electronic Frontier Foundation](https://privacybadger.org/) to view and exercise some control over who's tracking you, and also review the [EFF's Surveillance Self-Defense Guide](https://ssd.eff.org/). Also be aware of [internet censorship by different governments around the globe](https://en.wikipedia.org/wiki/Internet_censorship_and_surveillance_by_country), as compiled by Wikipedia, unless you happen to be reading this book in China, which has [blocked access to all of Wikipedia since April 2019](https://en.wikipedia.org/wiki/Censorship_of_Wikipedia). Finally, does the tool clearly explain whether the data you enter or the products you create will stay private or become public? For example, some companies offer free access to their visualization tools, but in exchange require you to make your data, charts, and maps publicly accessible. That tradeoff may be acceptable if you're working with open-access data and already plan to freely share your visualizations, as many journalists and scholars do. In any case, make sure the terms of service are clearly defined before you start using a tool.

*7. Collaborative*

Does the tool allow people to work together and co-create a data visualization? If so, does the tool allow different levels of access or version control to help prevent team members from accidentally overwriting each other's contributions? Prior generations of digital tools were designed primarily for solo users, in part to address security and privacy issues raised above. But today, many data visualization projects require access and input from multiple team members. Collaboration is essential for success. As co-authors of this book, who jointly wrote the text and co-created many of the visualizations, we favor a newer generation of tools designed for team work environments.

*8. Cross-Platform*

This category refers to both creating and consuming digital content. First, does the tool work across different computer operating systems? In this book, we highlight several tools that run inside any modern web browser, which usually (but not always) means they will operate on all major desktop and laptop computer platforms, such as Windows, Mac, Chromebook, and Linux. When necessary, we specify when a tool will only run on specific computer operating systems, and this often reduces access for people using lower-cost computers. Second, does the tool create visualizations that are responsive to different screen sizes? In other words, does it produce charts and maps that display satisfactorily on smaller devices, such as smartphones and tablets? In this book, we favor cross-platform tools that also display content responsively on smaller devices, but we do not necessarily expect that tools can be operated on small devices to create visualizations. In other words, when we say that a tool runs inside any modern web browser, we don't necessarily mean phone and tablet browsers, but sometimes they work there, too.

*9. Open-Source*

Is the tool’s software code publicly viewable? Can the code be modified and redistributed, so that other developers can suggest improvements, or build new features or extensions? We recognize that many developers rely on non-public proprietary code to sell their tools at a profit, and several of those appear in the book. But we also have been impressed with the number of high-quality data visualization tools offered under different types of open-source licensing arrangements, by sustainable communities of volunteer developers, non-profit organizations, and also for-profit companies who recognize some economic benefits of open-source code development. When recommending tools for this book, we highlight open-source options when available.

*10. Accessible for Visually-Impaired Readers*

Does the tool create visualizations that are accessible for visually-impaired readers? Although disability advocacy laws were passed decades ago, digital technology still lags behind and is slowly catching up, especially in the field of data visualization. But when selecting tools for this book, we highlight some such as [Datawrapper, which includes a built-in check for colorblindness](https://blog.datawrapper.de/colorblind-check/), and [Highcharts, which offers some chart types designed for low-vision people using screen readers](https://www.highcharts.com/demo/accessible-line).

Those are ten questions we ask ourselves when considering whether to add another entry to our digital toolkit. Your list may be longer, and include other considerations that often are harder to judge, such as a software developer's ethical business practices, labor policies, and contribution to the public good. Whatever criteria you value, make them explicit in your decision-making process, and inform people about what influences your choices.

When visualization designer Lisa Charlotte Rost reflected on her [fascinating experiment in recreating one chart with 24 different tools](https://source.opennews.org/articles/what-i-learned-recreating-one-chart-using-24-tools/), she concluded that "there are no perfect tools, just good tools for people with certain goals." On a related note, when digital historian Lincoln Mullen offered advice for [making prudent choices about digital tools](https://lincolnmullen.com/blog/how-to-make-prudent-choices-about-your-tools/), his first recommendation was: "The best possible tool is the one you're already using to get work done." Don't fall into the familiar trap of believing that your productivity will increase if only you began to use yet another new tool.^[@rostWhatLearnedRecreating2016; @mullenHowMakePrudent2013. See also criteria of educational tools by @wattersAudreyTestWhat2012a]

Now that you understand the factors driving our decisions, in the next section you'll see an overview of our tool recommendations, with a quick description and link to the chapter where we introduce each of them.

## Recommended Tools {- #recommended-tools}

When creating this book, we aimed to identify the most essential data visualization tasks that beginners are likely to face, and the digital toolkit needed to complete those tasks. In the prior section we listed ten factors that influenced our tool recommendations, such as being easy-to-learn, free or affordable, with powerful capacity. In this section, we'll list all of the tools recommended in the pages of this book, with a brief description and a reference to the chapter that discusses each in more detail.

Although we tried to minimize the size of our digital toolkit, we were surprised to discover that the final roster includes ZZZ [TODO INSERT NUMBER] tools! We agree that this number may still seem overwhelming at first to beginners. Let's be clear: your data visualization projects may only require you to use only a small number of these, or perhaps even just one tool. But it's important to be aware of the different types of tools, because you may not realize how they can help you if don't know that they exist.

TODO: Insert Table: Tools featured in this book, with links to relevant chapters, and how they rate on various criteria above


You may have other tool recommendations...and as we stated, tools change and evolve over time. So if you'd like us to consider another tool that's not already on the list, email or tweet us... explain what your recommendation would replace in the toolkit, and how it rates better on our criteria above.

## Use a Password Manager {- #password-manager}

TODO: add password manager tutorial to keep track of your accounts for the online tools you'll use in this book. The free and open-source BitWarden.com tool nicely integrates with most browsers and even smartphones.



### Summary {- #summary2}
TODO
Now you have a better sense of different types of data visualization tools, and how to make wise decisions when choosing among them...
The next chapter is designed to strengthen your skills for using the most common tool in our data toolkit: spreadsheets.
