## Chart Design Principles {#chart-design}
*last updated March 9, 2017*

Spot the difference between good and bad charts, based on this compilation of design principles from leading experts, with citations listed below to learn more.

1) Remember the **most important principle:** Find meaningful insights in your data, and create visualizations that help you tell these stories. All of the other details below are secondary.

2) Before you begin, ask yourself: Do I really need a chart to tell this data story? Or would a table or text alone do a better job?

3) Decide if the best way to communicate with your audience is with static charts (such as images printed on paper) or interactive charts (embedded in a website, with tooltip details and source links). Most of these principles apply to both types, but [this book features tools and tutorials](chart) to create interactive charts.

4) Understand basic chart vocabulary: title, labels, horizontal x-axis and vertical y-axis, data series, tooltip, source and credits. *image to come*

5) Identify the [chart type](chart) that best matches your story and data format.

6) Draw visual comparisons that are easy for readers to understand, rather than confusing them (adapted from Gourley p. 19). *image to come*

7) Do the math for your readers. Based on your data story, decide if you should show absolute numbers, percentages, or percent change (Wong pp. 23-25, 104-107). *image and link to come*

8) Order categories logically---either alphabetically, by value, or sequentially---depending on your data story (Gourley, p. 19; Wong pp. 70-71). *image to come*

9) For long labels, use horizontal bar charts instead of vertical column charts (Wong p. 66). *image to come*

10) On bar and column charts, start the vertical y-axis at zero, and choose natural increments (Wong pp. 51-52). But line charts do not need to start at zero, and can focus on specific ranges. See also the How to Lie with Charts and Maps chapter in this book. *image and link to come*

11) Beware of pie charts. Most readers cannot accurately estimate sizes of different slices. Consider other ways to show part-to-whole relationships, such as bar/column charts, or stacked bar/column charts (Few 2007, pp. 2-4; Wong p. 79).
*image to come*

12) If you choose to use a pie chart, then show no more than 5 slices, and places the largest slices closest to the top at 12 o'clock (Wong, pp. 74-75). *image to come*

13) Words matter as much as pictures.
- Add meaningful titles, labels, and annotations to draw attention to your data story.
- Keep typography simple, and use bold type sparingly to highlight your key insights (Wong p. 32; Knaflic pp. 107, 111).
- *image to come*

14) On static charts, label items directly when possible. (On interactive charts, designers may need to rely on tooltips and text.) Insert a legend in a logical place for readers (Wong, p. 56).

15) Add source credits and bylines---with links to view data tables and details---to build credibility and accountability.

16) Avoid “chart junk”--such as 3D perspective, shadows, and unnecessary ornaments---which distract readers from your data story. Never use 3D unless you are plotting three-dimensional data (Tufte p. *to come*, Wong p. 62, Knaflic p. 65). *image to come*

17) De-clutter charts (Knaflic pp. 91-98, 130-135).

18) Choose colors wisely.
- Use color to logically organize your data. Avoid random colors (Wong pp. 40, 44).
- Avoid bad combinations from opposite sides of color wheel, such as red/green or yellow/blue (Wong pp. 40, 44).
- Use contrast (such as color vs gray) to call attention to your data story (Knaflic pp. 87-88)
- *image to come*

See also [Map Design Principles](map-design) and [Tell Your Data Story](story) chapters in this book.

#### References {-}

Stephanie D. H. Evergreen, Effective Data Visualization: The Right Chart for the Right Data, (Los Angeles: SAGE Publications, Inc, 2016)

Stephen Few, Now You See It: Simple Visualization Techniques for Quantitative Analysis, (Oakland, Calif: Analytics Press, 2009)

Stephen Few, “Save the Pies for Dessert [critique of pie charts],” Visual Business Intelligence Newsletter, 2007, 1–14, http://www.perceptualedge.com/articles/visual_business_intelligence/save_the_pies_for_dessert.pdf

Stephen Few, Show Me the Numbers: Designing Tables and Graphs to Enlighten, Second edition (Burlingame, CA: Analytics Press, 2012)

Drew Gourley, How to Use Data Visualization to Win Over Your Audience, (Visage and Hubspot, June 2015), https://visage.co/content/data-viz-win-audience

Cole Nussbaumer Knaflic, Storytelling with Data: A Data Visualization Guide for Business Professionals, (Hoboken, New Jersey: Wiley, 2015)

Cole Nussbaumer Knalfic, "An Updated Post on Pies," StoryTelling with Data, February 16, 2017, http://www.storytellingwithdata.com/blog/2017/1/10/an-updated-post-on-pies

Wayne Lytle, Viz-O-Matic: The Dangers of Glitziness and Other Visualization Faux Pas, 1993 video shared on YouTube, https://www.youtube.com/watch?v=fP-7rhb-qMg

Isabel Meirelles, Design for Information: An Introduction to the Histories, Theories, and Best Practices Behind Effective Information Visualizations (Rockport Publishers, 2013), http://isabelmeirelles.com/book-design-for-information/

Tableau, Visual Analysis Best Practices: A Guidebook, n.d., http://www.tableau.com/sites/default/files/media/whitepaper_visual-analysis-guidebook_0.pdf.

Edward R. Tufte, Beautiful Evidence (Graphics Press, 2006)

“WTF Visualizations: Visualizations That Make No Sense,” 2017, http://viz.wtf.

xkcd, “University Website,” accessed February 12, 2017, https://xkcd.com/773/

Nathan Yau, “One Dataset, Visualized 25 Ways,” FlowingData, January 24, 2017, http://flowingdata.com/2017/01/24/one-dataset-visualized-25-ways/

Nathan Yau, “Best Data Visualization Projects of 2016,” FlowingData, December 29, 2016, http://flowingdata.com/2016/12/29/best-data-visualization-projects-of-2016/
