## Google Sheets Charts {#chart-google-sheets}
*last updated February 12, 2017*

Use Google Sheets (http://sheets.google.com), an easy drag-and-drop tool, to create basic interactive charts that you can embed in your website.

#### Tool Review {-}
- Pros:
  - Free and easy-to-learn tool on the collaborative Google Drive platform.
  - Edit, share, and publish interactive charts from your data, all in one spreadsheet.
- Cons:
  - Limited control over chart appearance.
  - Scatter charts cannot show data in tooltips.
  - Bubble charts cannot show small, uniform bubbles.
  - Cannot cite or link to source data inside the chart.
  - Cannot add annotations to highlight items inside charts.
  - For more powerful tools that require more skills, see tutorials in this book on [Tableau Public](scatter-chart-tableau/) and [Chart.js](chartjs).

#### Tutorials {-}
Follow the Google Sheet Chart tutorials in this book to create:

- [Column and Bar Charts](column-bar-google)
  - Grouped
  - Separated
  - Stacked
  - Histograms
- [Pie, Line and Area Charts](pie-line-area-google)
- [Scatter and Bubble Charts](scatter-bubble-google)

#### Learn more {-}
- [Google Sheet chart types help page](https://support.google.com/docs/answer/190718)
