## How to Lie with Maps {#how-to-lie-with-maps}
*By [Jack Dougherty](authors), last updated March 20, 2017*

One of the best ways to learn how to detect bias in data visualization is to intentionally manipulate a map, and tell two (or more) opposing stories with the same data. You’ll learn what to watch out for when viewing other people’s maps, and think more carefully about the ethical issues when you design your own.

This exercise was inspired by Mark S. Monmonier, *How to Lie with Maps, 2nd ed.* (University of Chicago Press, 1996), http://books.google.com/books?isbn=0226534219

First, scroll through this data on Median Household Income for Hartford-area towns, 2011-15, from American Community Survey 5-year estimates. Or right-click to [open this Google Sheet in a new tab](https://docs.google.com/spreadsheets/d/13bFHsXJtADIkUCGgjpO76RjrV0OAu62hzK-J3bXEVsk/edit#gid=556312122).

<iframe src="https://docs.google.com/spreadsheets/d/13bFHsXJtADIkUCGgjpO76RjrV0OAu62hzK-J3bXEVsk/pubhtml?gid=556312122&amp;single=true&amp;widget=true&amp;headers=false"></iframe>

Next, explore two different polygon maps of the same data. Use the drop-down menu to compare "Extreme Differences" versus "Uniform Equality"

<iframe src="https://jackdougherty.github.io/leaflet-how-to-lie-with-maps/" width="90%" height="500"></iframe>

Why are these two maps portray the same data so differently? To see the answer, look at the data ranges. . ..

** TO DO **

Create your own version...
