## Scatter Chart.js with CSV Data {#chartjs-scatter-csv}

Scatter charts (also *scatterplots*) are used to display data of 2 or more dimensions. The scatter chart below shows the relationship between household income and test performance for school districts in Connecticut. Using x- and y-axes to show two dimensions, it is easy to see that test performance improves as household income goes up.

<iframe src="https://handsondataviz.github.io/chartjs-templates/scatter-chart/index.html" width="100%" height=500 style="border: 0"></iframe>

Demo: https://handsondataviz.github.io/chartjs-templates/scatter-chart/index.html

Source and instructions: https://github.com//chartjs-templates/tree/master/scatter-chart

#### Going beyond two dimensions

To show more than two dimensions in scatter charts, one can:

* **color** each data point differently to show third dimension, eg use shades of red and green to show 5-year trend in test performance;
* **resize** each data point to display fourth dimension, eg number of students in each school district;
* use different **icons or glyphs** to display fifth dimension, eg circles for male students and squares for female students.

Remember not to overwhelm the viewer and communicate only the data that are necessary to prove or illustrate your idea.
