# Detect Lies and Reduce Bias {#detect}
TODO: Revise chapter

In the introduction, we lied to you... intentionally... by showing you visualizations that portrayed reality is very different ways.

In this chapter, you'll improve your lie detector skills in the realm of dataviz, and also work to reduce more subtle biases in your own dataviz.

While we like to believe data visualizations simply "tell the truth," when you dig further into this topic, you realize that there are multiple ways to represent reality.

People can mislead with charts and maps, but we can also create very different pictures of the truth....

You may be surprised to learn that there's not one *right* way to create a chart or a map. In the field of data visualization, we have only a few hard rules about how *not* to design, such as [REFER to chart and map design sections]. Even some of those "rules" are disputed.

In general, data visualization is guided by a general dictum to make "honest and useful decisions" (cite Datawrapper); Alberto Cairo adds that visualizations should be "truthful...functional....beautiful...insightful...."

That leaves a lot of room for interpretation... some of which is intentionally misleading, and some of it is thoughtlessly misinformed....unintentional.... but nevertheless sways how people view our visualizations...

In this chapter, you will learn how visualizations display the biases of the people and the software that create them.



While we cannot stop bias entirely, we can teach you to detect it in charts and maps made by other people, as well as those that you make, to improve your interpretation...

The best way to improve your lie detector skills is to learn various ways to intentionally manipulate data visualizations, to better understand how people might be lying to you. Since our book features hands-on tutorials, in the sections below we'll walk you through the steps of creating *biased* charts and maps, so that you'll know how to make *better* ones.

As the saying goes, it takes a thief to catch a thief: learn *how to lie* to avoid being fooled by other people's misleading charts and maps, and also so that you *tell the truth* in your own visualizations.

Since our book features hands-on lessons, in each section you'll learn how to create *biased* visualizations, so that you'll know how to make *better* ones. Just like it takes a thief to catch a thief... you need to learn how to lie in order to be more truthful in your visualizations...

These tutorials on "how to lie" were inspired by several sources....

- Darrell Huff, How to Lie with Statistics (W. W. Norton & Company, 1954), http://books.google.com/books?isbn=0393070875
- Mark S. Monmonier, How to Lie with Maps, 2nd ed. (University of Chicago Press, 1996), http://books.google.com/books?isbn=0226534219
- Nathan Yau, “How to Spot Visualization Lies,” FlowingData, February 9, 2017, http://flowingdata.com/2017/02/09/how-to-spot-visualization-lies/
- Alberto Cairo 2016
- Alberto Cairo 2019

## Avoid Bad Visualizations {- #bad-visualizations}
TODO: can this be reduced to 1-2 paragraphs with refs to chart and map design sections, rather than its own section?
Some visualizations are so poorly designed, with obvious errors, that we *can* declare these to be *wrong*.
Whether intentional or otherwise, no room for interpretation here... We warned you about some of these mistakes in the chart design and map design sections of this book.
- Examples: pie charts that add up to more than 100%
- hiding data by removing it from the chart (showing only high values, and omitting years with lower ones)


## How to Lie with Charts {- #how-to-lie-with-charts}
In this section, you'll learn how to avoid being fooled by misleading charts, and also how to make your own charts more honest, by intentionally manipulating the same data to tell opposing stories. In the first half, you will *exaggerate* small differences in a column chart to make them seem larger. In the second, half, you will *diminish* the rate of growth in a line chart to make it appear more gradual. Together, these tutorials will teach you to watch out for key details when reading other people's charts, such as the vertical axis and aspect ratio. Paradoxically, by demonstrating *how to lie*, our goal is to teach you to *tell the truth* and to think more carefully about the ethics of designing your data stories.

In the first half of this tutorial, we'll examine data about the economy, a topic that's often twisted by politicians to portray it more favorably for their perspective. The Gross Domestic Product (GDP) measures the market value of the final goods and services produced in a nation, which many economists consider to be the primary indicator of economic health. (Interestingly, not everyone agrees because GDP does not count unpaid household labor such as caring for one's children, nor does it consider the distribution of wealth across a nation's population.) We downloaded US GDP data from the [US Federal Reserve open-data repository](https://fred.stlouisfed.org/series/GDP), which is measured in billions of dollars and published quarterly, with seasonal adjustments to allow for better comparisons across industries that vary during the year, such as summer-time farming and tourism versus Christmas-time gift shopping. Your task is create a *misleading* column chart that *exaggerates* small differences to make them appear larger in the reader's eye.

1. Open the [US GDP mid-2019 data in Google Sheets](https://docs.google.com/spreadsheets/d/1teB2Pw2lNpFjE_GCNmeqVNURSid36IMrWUROpPZMScA/edit#gid=0), and go to *File > Save As* to create a copy that you can edit in your own Google Drive. We'll create charts in Google Sheets, but you can also download the data to use in a different chart tool if you prefer.

2. Examine the data and read the notes. To simplify this example, we show only two figures: the US GDP for the 2nd quarter (April-June) and the 3rd quarter (July-September) in 2019. The 2nd quarter was about $21.5 trillion, and the third quarter was slightly higher at $21.7 trillion. TODO: DECIDE whether to add this: If we calculated the percent change, or (21747 - 21540)/21540 = 0.0096 = 0.96%, that's a growth rate of just under 1 percent.

3. Create a Google Sheets column chart in the same sheet using the *default* settings, although we never automatically accept them as the best representation of the truth. In the *data* tab, select the two columns, and go to *Insert > Chart*, as you learned when we introduced [charts with Google Sheets in Chapter 6](chart-google.html). The tool should recognize your data and automatically produce a column chart, as shown in FIG TODO. In this default view, with the zero baseline for the vertical axis, the difference between $21.5 versus $21.7 trillion looks relatively small to the reader.

4. *Lie by reducing the vertical axis.* Click on the three-dot kebab menu to open the *Chart editor* and select the *Customize* tab. Scroll down to the vertical axis settings, and change the minimum to 21500 and the maximum to 21800, as shown on the right side of FIG TODO. Although the data remains the same, those small differences now appear much larger in our eyes because you've manipulated the vertical scale. Only people who read charts closely will notice this trick. The political candidate who's campaigning on rising economic growth will thank you!

FIG TODO MERGE

However, you've also violated one of the [cardinal rules about chart design in chapter 6](chart-design.html): bar and column charts *must* start at the zero baseline, because they represent value using *length*. Therefore, in the eyes of data visualization experts, your misleading chart is wrong, and the default chart with the zero baseline is a better representation of the truth. But let's move on to a different example where the rules are not as clear.

In the second half of this tutorial, we'll examine data about climate change, one of the most pressing issues we face on our planet, yet deniers continue to resist the new reality, and some of them twist the facts.[TODO: Cite Cairo examples]. In this tutorial, we'll examine global temperature data from 1880 to the present, [downloaded from the NASA, the US National Aeronautics and Space Administration](https://climate.nasa.gov/vital-signs/global-temperature/). It shows that the mean global temperature has risen about 1 degree Celsius (or about 2 degrees Fahrenheit) during the past fifty years, and this warming has already begun to cause glacial melt and rising sea levels. Your task is to create *misleading* line charts that *diminish* the appearance of rising global temperature change in the reader's eye.^[The inspiration for this specific tutorial came from a high school classroom activity created by the NASA Jet Propulsion Laboratory (JPL), as well as visualization expert Alberto Cairo's analysis of charts by climate change deniers. @nasajplEducatorGuideGraphing2017; @cairoHowChartsLie2019, pp. 65-67, 135-141.]

1. Open the [global temperature change 1880-2019 data in Google Sheets](https://docs.google.com/spreadsheets/d/1Npc7ozRjlsgRLLEV_B5zBvqyRqL6akE2qrEIGegHfGU/edit#gid=0), and go to *File > Save As* to create a copy that you can edit in your own Google Drive.

2. Examine the data and read the notes. Temperature change refers to the mean global land-ocean surface temperature in degrees Celsius, estimated from many samples around the earth, relative to the temperature in 1951-1980, about 14°C (or 57°F). In other words, the 0.98 value for 2019 means that global temperatures were about 1°C above normal that year. Scientists define the 1951-80 period as "normal" based on standards from NASA and the US National Weather Service, and also because it's a familiar reference for many of today's adults who grew up during those decades. While there's other ways to measure temperature change, this data from NASA's Goddard Institute for Space Studies (NASA/GISS) is generally consistent with data compiled by other scientists at the [Climatic Research Unit](http://www.cru.uea.ac.uk/) and the [National Oceanic and Atmospheric Adminstration](https://www.ncdc.noaa.gov/cag/global/time-series) (NOAA).

3. Create a Google Sheets line chart in the *data* tab by selecting the two columns in the *data* tab, then *Insert > Chart*. The tool should recognize your time-series data and produce a *default* line chart, though we never automatically accept it as the best representation of the truth. Click on the three-dot kebab menu to open the *Chart editor* and select the *Customize* tab. Add a better title and vertical axis label, using the notes to clarify the source and how temperature change is measured, as shown in FIG TODO

temperature-default.png
https://docs.google.com/spreadsheets/d/e/2PACX-1vRBJy0vWBN1z49hE8c7vxF_ZiTNKF5RjQ2vpJ-aVfsdNpNYgcMu1cH2zAh90v713vcMmrs6kVlSgQkV/pubchart?oid=557710802&format=interactive

Now let's use three methods to create *misleading* charts:

5. *Lie by lengthening the vertical axis.* We'll use the same method as shown in the first half of this tutorial, but in the opposite direction. In the Google Sheets chart editor, customize the vertical axis by changing the minimum value to negative 5 and the maximum to positive 5, as shown in FIG TODO. By increasing the length of the vertical scale, you flattened our perception of the rising line, and cancelled our climate emergency...but not really.

temperature-axis-annotated.png

4. *Lie by stretching the chart to change its aspect ratio.* In your Google Sheet, click the chart and drag the sides to make it very short and wide, as shown in FIG TODO. Image measurements as listed in width by height, and we calculate the aspect ratio as width divided by height. Since the default chart is 600 x 370 pixels, its aspect ratio is about 1.6 to 1. But the stretched-out chart is 1090 x 191 pixels, and its ratio is about 5.7 to 1. By increasing the aspect ratio, you have flattened our perception of the rising line, and cancelled our climate crisis once again...but not really.

temperature-aspect-annotated.png

5. *Lie by adding more data and a dual vertical axis* Let's add more data to make your chart even more misleading! In the Google Sheet, go to the tab named *temp+GDP*, where you will see temperature change plus a new column: US Gross Domestic Product (GDP) in billions of dollars from 1929 to 2019, downloaded from the [US Federal Reserve](https://fred.stlouisfed.org/series/GDPA). (We deleted temperature rows prior to 1929 to make them match with available GDP data.) Select all three columns and *Insert > Chart* to produce a default line chart with two data series: temperature (in blue) and US GDP (in red).

6. In the *Chart editor*, select *Customize* and scroll down to *Series*. Change the drop-down menu from *Apply to all series* to *US GDP*. Just below that in the *Format* area, change the *Axis* menu from *Left axis* to *Right Axis*, which creates another vertical axis on the right side of the chart, connected only to the US GDP data, as shown in FIG TODO

temperature-gdp-axis-setup.png

7. In the *Chart editor > Customize* tab, scroll down and you will now see separate controls for *Vertical Axis* (the left side, for temperature change only), and a brand-new menu for *Right Axis* (for US GDP only), as shown in FIG TODO

temperature-right-axis.png

8. Finish your misleading chart by adjusting *Vertical Axis* for temperature change, but with even more exaggeration than you did in step 5 above. This time, change the minimum value to 0 (to match the right-axis baseline for US GDP) and the maximum to 10, to flatten the temperature line even further. Add a title, source, and labels to make it look more authoritative, as shown in FIG TODO. By lowering our perception of the temperature line in comparison to the steadily rising GDP line, you've misled us into ignoring the consequences of climate change while we enjoy a long-term economic boom! Furthermore, the GDP data is *not* adjusted for inflation, so you've double-misled us by comparing 1929 dollars to 2019 dollars. Finally, since you accepted the default colors assigned by Google Sheets, the climate data is displayed in a "cool" blue, which sends our brain the opposite message of rising temperatures and glacial melt. So we'll count this as a triple! TODO: Decide whether to break non-comparable data and color into separate paragraphs.

temperature-gdp-final-annotated.png

TODO: There are many other ways to lie with charts.... for example, lie with 3D and perspective (see Cairo 2019 p58)...

Now you've created three *misleading* charts. But are any of them *wrong*? Do they violate any rules of data visualization? If you're the type of person who prefers to clearly divide things into *good* versus *bad*, our answer may disappoint you. Alberto Cairo warns us that [TODO insert quote here about visualization is more of an art than a science... all visualizations are simply models of reality, not the truth... we can only make better representations of the truth...].

In the first half of the tutorial with the US GDP column chart, you clearly violated the zero-baseline rule when you started the vertical axis at a number other than zero. Column (and bar) charts *must* begin at zero, because they use *height* (and *length*) to represent value, as we described in the [chart design section of Chapter 6](chart-design.html). Readers cannot determine if a column is twice as high as another column unless both begin at the zero baseline.

But the zero-baseline rule does *not* apply to line charts, Cairo reminds us, because those represent the *position* and *angle* of the line. Readers determine the meaning of line charts by their shape, rather than their height, so the baseline is irrelevant. This means that the flattened line chart for temperature change you created in step 5 may mislead readers, but it's not wrong, as long as you labeled it correctly for readers who inspect these details.^[@cairoHowChartsLie2019, p. 61.]

What about the warped aspect ratio you applied to the temperature chart in step 6? While it's certainly designed to mislead readers, Cairo acknowledges that it is not *wrong* because it does not violate a clearly-defined rule of data visualization. Cairo prefers to set the aspect ratio to be similar to the rate of change shown in the line chart....[TODO describe and cite passage about this... and there's no set rule....]

What about the dual-axis chart you created in step 7 to compare global temperature change versus US GDP? We agree with many visualization experts who discourage using dual-axis charts because they confuse most readers and create mischief. Even though both axes began at zero, the left-side temperature scale has a top level of 10 degrees Celsius, which is not reasonable given the context of the data. A *scatter or bubble chart*, which is designed to compare two or more variables, would be a better way to plot global temperature change and US GDP over time. [TODO: Should we show this chart here?] Furthermore, a better chart would compare appropriate data, such as real GDP that has been adjusted into constant dollars.

TODO:FINISH IDEA: So if none of the temperature change charts are technically *wrong*, are any of them *right*? Or in Cairo's definition, which chart offers the most truthful representation of global temperature change? ... interestingly, the Google Sheet default chart you created in step 3 meets most of our criteria: [check aspect ratio]. In any case, never accept the defaults automatically....

Now that you've learned about how to lie with charts, you'll build on these skills in the next section about lying with maps.

## How to Lie with Maps {- #how-to-lie-with-maps}
- TODO: reorganize exercise into more distinctive parts and sample data

Before we leap into lying, let's make sure we avoid common mistakes when making maps, especially choropleth maps that use shading or color to represent values in geographic areas. The most common mistake is to use raw counts rather than rates or percentages... You need to normalize the data, as we describe in chapter.... .forgetting this will simply show pop density; Cairo 2019 p132)

One of the best ways to learn how to detect bias in data visualization is to intentionally manipulate a map, and tell two (or more) opposing stories with the same data. You’ll learn what to watch out for when viewing other people’s maps, and think more carefully about the ethical issues when you design your own. This exercise was inspired by Mark S. Monmonier, *How to Lie with Maps, 2nd ed.* (University of Chicago Press, 1996), http://books.google.com/books?isbn=0226534219

- Lie (or mislead?) with ranges
- lie with color choices

Other ways to lie with maps (which may be too hard to display here?)
- Lie with map area
- Lie with projection (or discuss as related to map area?)


which map is right?
Both maps make valid interpretations of the data, but generate very different impressions. You may be surprised to learn that mapmakers have few universal guidelines when selecting ranges or colors, other than a general dictum to make “honest and useful” decisions. Different mapmakers could choose to divide the legend into three, or four, or five ranges, and all would be correct. Furthermore, they could choose to divide ranges into equal intervals (such as quartiles or quintiles) or intervals that vary according to patterns in the data (such as standard deviations from the mean).

Cairo advises: make multiple histogram charts, with different numbers of buckets & bucket sizes -- TODO: rewrite Map chapter to include this advise and insert histogram exercise there



First, scroll through this data on Median Household Income for Hartford-area towns, 2011-15, from American Community Survey 5-year estimates. Or right-click to [open this Google Sheet in a new tab](https://docs.google.com/spreadsheets/d/13bFHsXJtADIkUCGgjpO76RjrV0OAu62hzK-J3bXEVsk/edit#gid=556312122).

<iframe src="https://docs.google.com/spreadsheets/d/13bFHsXJtADIkUCGgjpO76RjrV0OAu62hzK-J3bXEVsk/pubhtml?gid=556312122&amp;single=true&amp;widget=true&amp;headers=false"></iframe>

Next, explore two different polygon maps of the same data. Use the drop-down menu to compare "Extreme Differences" versus "Uniform Equality"

<iframe src="https://handsondataviz.github.io/leaflet-how-to-lie-with-maps/" width="90%" height="500"></iframe>

Why are these two maps portray the same data so differently? To see the answer, look at the data ranges. . ..

** TO DO **

Create your own version...

TODO: Add section on how interactive maps such as Google Maps change borders and data depending on the internet address of the user

## How to Lie with Words {- #how-to-lie-with-words}

Now that we've focused on charts and maps, think more carefully about the words we choose when designing our visualizations...

Framing Bias: Watch for negative versus positive framing and how it affects readers. For example, British statistician David Spiegelhalter notes that US hospitals report *mortality rates*, while UK hospitals report *survival* rates. When considering the risks of a surgical procedure for member of your family, a 5 percent mortality rate sounds worse than a 95 percent survival rate, even they're mathematically identical. Furthermore, augmenting the rate with raw numbers (such as 20 deaths out of 400 patients) raises the impression of risk even higher, because we begin to imagine real people's lives, not abstract percentages.^[@spiegelhalterArtStatisticsLearning2019, pp. 22-5]

Poorly-worded percentages: Percent Change versus Percentage Point Difference

## Different Types of Data Bias {- #data-bias}

Bias occurs when we unfairly favor one view over another. Different types of bias....(we already mentioned statistical biases in the Compare Appropriate Data chapter...)

We use the term to refer to biased people who prejudge something before evaluating the evidence. While some forms of bias are clearer to recognize, such as racial or gender bias,....Some biases are baked into human cognition and hard to avoid in data viz, unless you call it out

- Pattern Bias: tendency to see patterns in random data. Avoid it by remind readers that data is noisy and use statistical tests to determine likelihood of results due to change, covered in many books on statistical analysis.
- Confirmation Bias: accept claims that fit our preconceived notions...(see dataviz experiments in Cario book, Thaler?). Avoid it by looking at data with open eyes, and search out competing interpretations

We also refer to biases that are baked into the software that humans create.
- Algorithm or machine learning bias: human-written code, or machine-learning that follows inductive reasoning standards set up by humans, can lead to biased results, especially in facial recognition across racial groups, or discrimination in home lending. examples: https://www.nytimes.com/2019/08/20/upshot/housing-discrimination-algorithms-hud.html; https://www.brookings.edu/blog/techtank/2020/04/16/why-a-proposed-hud-rule-could-worsen-algorithm-driven-housing-discrimination/

## Reducing Racial Bias in Visualizations {- #racial-bias}
- Example: Map with “empty” land ignoring indigenous people https://twitter.com/indigenia/status/1308406887231246337?s=12
- sidenote: that wasn't how the original map creator designed or labeled the map, but others interpreted it this way
- how to address: clarify map biases....


### Summary {- #summary14}
TODO
