## Section 2 Chart 2 Peer Review Sample with Notes {#peer-2-chart-2-notes}

Nations with the highest percentage of female students enrolled in Data Visualization for All are the Ukraine (51 percent) and Turkey (47 percent), based on preliminary data for those with high enrollment levels (25 or more students).

<iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/1hvr0fOFUg4xm9I3L1WFzpHZvRqIRl3w8S9pMNnVg9rQ/pubchart?oid=2012433343&amp;format=interactive"></iframe>

View the <a href="https://docs.google.com/spreadsheets/d/1hvr0fOFUg4xm9I3L1WFzpHZvRqIRl3w8S9pMNnVg9rQ/edit#gid=1391209592">preliminary data for 21 Feb 2017</a> from http://DataVizForAll.org

#### Evaluate:
1. Story: Did the author clearly tell a meaningful story about the data, with text and visuals?
  - Yes, this insight on gender differences in student enrollments across nations is a meaningful story.
2. Chart Type: Did the author choose a chart type that best matches their data story?
  - Yes, this stacked horizontal bar chart is a good match for showing part-to-whole relationships (gender by percentage) between different nations.
3. Embed: Did the author embed an interactive chart into the web page?
  - Yes, when you float your cursor over it, the interactive chart tooltip shows data labels and values.
4. Good Design: Did the author follow principles of good chart design?
  - Yes, the chart demonstrates good design principles, such as:
    - Sorting data into a meaningful order
    - Using color contrast (blue vs grays) to highlight percentages of female students
