## Section 3 Peer Review Sample 2 with Notes

#### My Leaflet map
<iframe src="https://datavizforall.github.io/leaflet-map-simple-instructor-sample" width="90%" height=350></iframe>

#### My Highcharts scatter chart
<iframe src="https://datavizforall.github.io/highcharts-scatter-csv-instructor-sample" width="90%" height=425></iframe>

#### Evaluate
1. Leaflet map and title: Did the author embed an interactive Leaflet map with a new title?
  - Yes, the title in this map has changed from the original template

2. Leaflet map layers: Did the author add controls that toggle on/off different map layers?
  - Yes, this map contains map layer controls.

3. Leaflet point markers: Did the author upload a new set of markers, with pop-ups that show titles for each point?
  - Yes, this map contains new points that were added to the original template.

4. Highcharts scatter chart: Did the author embed an interactive Highcharts scatter chart with a new title and axis labels?
  - Yes, this chart contains a new title and axis labels.

5. Highcharts data tooltips: Did the author upload a new set of data, with tooltips that show labels and details for each point?
  - Yes, this chart contains a new set of data points that were uploaded to the original.

6. Additional comments for the author. What works well? What could be improved?
