# Stuff To Do {#stuff-to-do}
for book-in-progress

#### Discuss with Ilya {-}
- review our Bookdown workflow and style guide and clarify this in chapter 15-bookdown.Rmd
  - confirm if my internal cross-reference link format is properly designed
    - compare with bookdown guide: https://bookdown.org/yihui/bookdown/cross-references.html
    - note that cross-ref for [to-do](#to-do) points to first instance of any section in book named `#to-do`
  - decide on header style
  - decide if we want to include automated footer (authors, website, licensing, etc.)
  - discuss pros/cons of inserting images in Markdown format (current version) vs. bookdown templating (better support for future PDF version?)
- discuss the relationship between the book and the edX course https://www.edx.org/course/data-visualization-all-trinityx-t005x
  - I have no interest in updating the edX course, but Trinity offers a small financial incentive to do so
  - the edX course has some quiz-type content that we *could* integrate into the book
  - discuss if/how we wish to link to the edX course: internal chapter, external site, or neither. Search project for "Enroll" and implement
- study analytics for edX, GitBook, Google, and YouTube to identify most frequently-used pages & resources to prioritize what we work on
- move all of the code templates on GitHub from JackDougherty to DataVizForAll, and change book references (am willing to pay hourly for these not-so-interesting but important tasks)
- discuss next steps toward publication of print version


#### Jack's list {-}
- search project for "TO DO" and "TODO" and "to come" and "UPDATE" references, and write content
- rewrite introductory sections to shift perspective from "I" to "We"
- update licensing and About the Authors
- decide if unwritten "Upload GeoJSON Data to a Leaflet Map template on GitHub" chapter belongs in Leaflet section
- rethink BatchGeo chapter, since they now have strict limits on free maps (100 views) and our Batch Geo Demo no longer works
- decide whether to remove all reference to Google Fusion Templates, or keep page to explain how Google deprecated them
- data folder includes us-states files, but not yet listed or linked in 03.1-census
- search project for "Donate" and decide whether to delete or change references to our own Donate button
  ```html
  <br /><strong>Improve this book: <a href="https://www.datavizforall.org/donate">Donate to DataViz students</a></strong> and <strong><a href="https://www.datavizforall.org/introduction/how.html">add comments or revisions</a></strong>.
  </div>
  ```
- decide if book will include .bib references. If yes, then restore these lines in index.Rmd
  ```markdown
  bibliography: book.bib
  biblio-style: apalike
  link-citations: true
  ```
