## Alternative Book Authoring-Publishing Tools {- #alternative}

Before leaping into [Bookdown](https://bookdown.org) or any other tools for authoring and/or publishing book-length works, clarify your goals and consider the costs and benefits of different approaches. Here's a short list of alternatives we considered, and our notes on how they addressed our specific goals. Your experience may differ from ours, and tools are continually evolving, so we encourage feedback [on Twitter](https://twitter.com/doughertyjack).

- Conventional word processors: Most authors work primarily with text, and are satisfied with a traditional book-publishing workflow that begins with composing in Microsoft Word or LibreOffice, then handing it off to a publisher for review, copyediting, layout, and distribution. But our book is designed to blend text and interactive digital media, and to publish book products in multiple formats: HTML, PDF, DOCX, and Markdown. Traditional word processors do not efficiently achieve this goal.

- Advanced word processors: [Scrivener](https://www.literatureandlatte.com/scrivener) by Literature & Latte is a powerful word processor and outlining tool designed to help authors see both "the forest and the trees" of book-length manuscripts. Although Scrivener supports a different version of Markdown, the tool was not designed to integrate interactive maps and charts into text, nor does it support multi-author collaboration, or sharing files on a public repository.

- Cloud-based word processors: [Google Docs](http://docs.google.com) and other cloud-based word processors allow authors to write collaboratively in real-time, comment on each other's work, and share drafts in semi-public or public venues for early reader feedback. Furthermore, installing the [Docs to Markdown by Ed Bacher](https://github.com/evbacher/gd2md-html/wiki) allows you to convert Google Doc files into Markdown format (for easier conversion to other platforms, such as Bookdown) or HTML format (for the web). Although Google Docs can display static images of interactive maps and videos, and links to online versions, it was not designed to display interactive iframes, nor to publish book-length editions to the web or PDF formats.

- [GitBook](https://www.gitbook.com) is a collaborative publishing platform that is primarily designed for producing online documentation. Authors can embed some interactive content, share their work through a GitHub repository, and exercise version control. The GitBook layout with its collapsible table of contents is well-designed, and has been integrated as a style into Bookdown. But GitBook is not designed to produce exportable book files (and the PDF export is only available as a beta feature for paid business-level subscribers). Furthermore, GitBook does not support citation tools that some authors require.

- [WordPress.org](http://wordpress.org) is an open-source web authoring platform, used by over 33 percent of the top 10 million websites as of 2019. Users can create a free account on [WordPress.com](http://wordpress.com), or freely download the WordPress software and run a self-hosted version on a server, which requires developer skills or a third-party service, such as [ReclaimHosting.com](http://reclaimhosting.com). Although WordPress creates web pages, it was not designed to produce PDFs or print books, and it's not easy for authors to edit book-length manuscripts on a WordPress platform.

- [Pressbooks](http://pressbooks.com) is an open-book publishing platform built on an open-source variation of WordPress Multisite, which produces books in different formats: web, print (PDF), ebooks (ePUB), etc. Authors can pay to publish on the Pressbooks.com platform or a third-party service such as [ReclaimHosting.com](http://reclaimhosting.com), or [freely download the software](https://github.com/pressbooks) to run on a server, which requires developer skills. Although Pressbooks is a powerful tool, it requires an investment of time and resources to install and maintain its platform, dependencies, and updates. Also, creating a book in Pressbooks requires authors to compose directly in the WordPress-style editor, or copy-and-paste content from word processor to web platform, which requires continually updating back-and-forth to keep both versions the same. By contrast, composing in Bookdown is simpler because there is only one version of the book manuscript, from which all book products are generated.

- [Scalar](https://scalar.me/) is an open-source scholarly authoring and publishing platform by the Alliance for Networking Visual Culture, with support from the Mellon Foundation and the National Endowment for the Humanities. The platform was created primarily for authors to assemble born-digital book-length works online, with media from multiple sources, and it allows multi-author collaboration. But the platform was not designed to produce PDFs or print books, so was not considered for this book. See examples of online-only works at <https://scalar.me/anvc/scalar/showcase/>. Users can freely register to create works on the Scalar platform hosted by the University of Southern California at <http://scalar.usc.edu/works/>.

- [Manifold](https://manifoldapp.org) is an open-source scholarly publishing platform created through a collaboration by the University of Minnesota Press, the Graduate Center at the City University of New York, and Cast Iron Coding, with funding from the Mellon Foundation. The platform was designed primarily for authors to integrate digital media into their texts, and also for readers to view and annotate drafts and finished books online. It appears that print book production is handled separately. Since installing Manifold on a server requires developer skills, most authors will need to work directly with a participating publisher to access the tool. The Manifold platform can ingest texts written in Markdown, Microsoft Word, and other formats.

- [Fulcrum](https://www.fulcrum.org/) is an open-source scholarly publishing platform created University of Michigan Library and Press in collaboration with several partners, with initial funding from the Mellon Foundation. The platform was designed primarily for authors to integrate digital media into book-length works, which readers can view online or in e-book formats or print formats. Since the Fulcrum platform is hosted on the publisher's server, authors will need to work directly with a participating publisher to access the tool.
